# Jekyll config
#
# This is a stripped-down version of the standard config. See here for a full example:
#     https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml

title: Sample Jekyll Site
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a Jekyll site created directly on GitHub
baseurl: "/jekyll-raw" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# Make it look nicer
theme: minima
# List all the posts on the home page
plugins:
  - jekyll-feed
