# Jekyll config
#
# This is a stripped-down version of the standard config. See here for a full example:
#     https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml

title: Sample Jekyll Site
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a Jekyll site created directly on GitHub
baseurl: "/jekyll-raw" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# GitHub still uses minima 2.5.1, which shows the title twice in the footer if there's no author.
# (source: https://github.com/jekyll/minima/blob/v2.5.1/_includes/footer.html)
author: Colin

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# Make it look nicer
theme: minima
# List all the posts on the home page
plugins:
  - jekyll-feed

# Only show specific pages in the header, not all directories
header_pages:
  - about.md
